### ISSUE TITLE
Help understanding how to use caching

### ISSUE THREAD

**Issue by maqen** [errorstudio/contentful_rails#6]
Thanks for a great gem, eases use of contentful in rails apps allot!

But I'm having a hard time understand how I would go about adding caching to my application. Can fragment caching be used?

```ruby
<% @car = Car.first %>
<% cache(@car) %>
    <%= @car.name %>
```

Is it possible to add a section in readme or similar with some small code examples on how to use cache (updated_at) for views and in controllers?

**Comment by edtjones** [comment]
Hi @maqen I'll improve the readme. In short, though, what you're doing should work ok. If `@car` is a ContentfulModel object, it should respond to cache_key which means Rails views will cache OK.

You can prove this out by doing the following in a console session:

```
c = Car.first #should be an instance of Car, which inherits from ContentfulModel::Base
c.cache_key #should return a string, representing the cache key for this object
```

Hope that helps?

**Comment by maqen** [comment]
But how can I get ```Car.first``` without hitting the contentful api? Don't see the point in caching like this then?

**Comment by edtjones** [comment]
Hi @maqen you're right - this doesn't obviate the need for an API hit to get a collection of `Car` objects, but it would stop you having to make a call to get more child data if you have a parent/child relationship in Contentful.

The only thing which is cached (by default) is the timestamp - so the logic goes like this:

* Get collection of things (does require API hit)
* cache view partial based on cache key (which includes the cached timestamp component)
  * if the timestamp doesn't exist, you need to render the whole partial
  * if the timestamp _does_ exist, render the view you've already cached

This doesn't mean your site will freewheel if contentful is down, and there is still a dependency on contentful for the data. But the view rendering is fast.

It's not a panacea. The proper way to do this would be to receive the webhook data and cache an entire model object. Unfortunately that requires some refactoring of the Contentful gem to create an object which looks identical, from either the API response or the webhook callback data. See https://github.com/contentful/contentful.rb/issues/55 - if you fancy attacking that I know @pxlpnk and I would be grateful :-)

Hope that helps?
